// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/account" | "/dashboard" | "/generator" | "/new-project" | "/projects" | "/projects/[projectId]" | "/sign-in/[[...sign-in]]" | "/sign-up/[[...sign-up]]"
type AppRouteHandlerRoutes = "/api/ai/edit" | "/api/ai/generate" | "/api/ai/regenerate-section" | "/api/deploy" | "/api/projects" | "/api/projects/[projectId]" | "/api/projects/[projectId]/domains" | "/api/projects/[projectId]/duplicate" | "/api/projects/[projectId]/preferred-domain" | "/api/projects/[projectId]/seo"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/account": {}
  "/api/ai/edit": {}
  "/api/ai/generate": {}
  "/api/ai/regenerate-section": {}
  "/api/deploy": {}
  "/api/projects": {}
  "/api/projects/[projectId]": { "projectId": string; }
  "/api/projects/[projectId]/domains": { "projectId": string; }
  "/api/projects/[projectId]/duplicate": { "projectId": string; }
  "/api/projects/[projectId]/preferred-domain": { "projectId": string; }
  "/api/projects/[projectId]/seo": { "projectId": string; }
  "/dashboard": {}
  "/generator": {}
  "/new-project": {}
  "/projects": {}
  "/projects/[projectId]": { "projectId": string; }
  "/sign-in/[[...sign-in]]": { "sign-in"?: string[]; }
  "/sign-up/[[...sign-up]]": { "sign-up"?: string[]; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
